-- --------------------------------------------------------
-- 主机:                           127.0.0.1
-- 服务器版本:                        5.6.24 - MySQL Community Server (GPL)
-- 服务器操作系统:                      Win32
-- HeidiSQL 版本:                  9.2.0.4947
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 导出 thesisexperiment 的数据库结构
CREATE DATABASE IF NOT EXISTS `thesisexperiment` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `thesisexperiment`;


-- 导出  表 thesisexperiment.featureextraction_lie128_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_lie128_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小2s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_lie128_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_lie128_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小2s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_lie32_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_lie32_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小0.5s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_lie32_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_lie32_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小0.5s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_lie64_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_lie64_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小1s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_lie64_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_lie64_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小1s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_sit128_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_sit128_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小2s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_sit128_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_sit128_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小2s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_sit32_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_sit32_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小0.5s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_sit32_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_sit32_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小0.5s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_sit64_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_sit64_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小1s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_sit64_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_sit64_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小1s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_stand128_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_stand128_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小2s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_stand128_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_stand128_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小2s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_stand32_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_stand32_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小0.5s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_stand32_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_stand32_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小0.5s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_stand64_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_stand64_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小1s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_stand64_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_stand64_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小1s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_walk128_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_walk128_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小2s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_walk128_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_walk128_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小2s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_walk32_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_walk32_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小0.5s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_walk32_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_walk32_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小0.5s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_walk64_33 结构
CREATE TABLE IF NOT EXISTS `featureextraction_walk64_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_range` text NOT NULL COMMENT '单位：mg',
  `HIP_range` text NOT NULL COMMENT '单位：mg',
  `LUA_range` text NOT NULL COMMENT '单位：mg',
  `RKN_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_HIP_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_LUA_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_RKN_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的数据信息（采样频率64hz，窗口大小1s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.featureextraction_walk64_99 结构
CREATE TABLE IF NOT EXISTS `featureextraction_walk64_99` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `RKN_accX_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mean` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mean` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mean` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_variance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_variance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_variance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_mad` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_mad` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_mad` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_rms` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_rms` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_rms` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_iqr` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_iqr` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_range` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_range` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_range` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_kurtosis` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_kurtosis` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_skewness` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_skewness` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_covariance` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_covariance` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_accY_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_accZ_correlation` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_accX_correlation` text NOT NULL COMMENT '单位：mg',
  `RKN_accX_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accY_energy` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accX_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accY_energy` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accX_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accY_energy` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ_energy` text NOT NULL COMMENT '单位：mg',
  `locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；3：Sit；4：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='特征提取后的lie数据信息（采样频率64hz，窗口大小1s，重叠率50%，提取特征：均值，方差，平均绝对误差，均方根，四分位差，\r\n * 极差，峰度，偏度，协方差，能量，相关系数量）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.lie 结构
CREATE TABLE IF NOT EXISTS `lie` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `Time` text NOT NULL COMMENT '单位：ms',
  `RKN_accX` text NOT NULL COMMENT '单位：mg',
  `RKN_accY` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ` text NOT NULL COMMENT '单位：mg',
  `HIP_accX` text NOT NULL COMMENT '单位：mg',
  `HIP_accY` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ` text NOT NULL COMMENT '单位：mg',
  `LUA_accX` text NOT NULL COMMENT '单位：mg',
  `LUA_accY` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ` text NOT NULL COMMENT '单位：mg',
  `Locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；4：Sit；5：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Locomotion=5(Lie)';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.lie_33 结构
CREATE TABLE IF NOT EXISTS `lie_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `Time` text NOT NULL COMMENT '单位：ms',
  `RKN` text NOT NULL COMMENT '单位：mg',
  `HIP` text NOT NULL COMMENT '单位：mg',
  `LUA` text NOT NULL COMMENT '单位：mg',
  `Locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；4：Sit；5：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Locomotion=5(Lie)';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.preprocessingdata 结构
CREATE TABLE IF NOT EXISTS `preprocessingdata` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `Time` text NOT NULL COMMENT '单位：ms',
  `RKN_accX` text NOT NULL COMMENT '单位：mg',
  `RKN_accY` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ` text NOT NULL COMMENT '单位：mg',
  `HIP_accX` text NOT NULL COMMENT '单位：mg',
  `HIP_accY` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ` text NOT NULL COMMENT '单位：mg',
  `LUA_accX` text NOT NULL COMMENT '单位：mg',
  `LUA_accY` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ` text NOT NULL COMMENT '单位：mg',
  `Locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；4：Sit；5：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='经过预处理后的数据（预处理：删除含有缺失数据或是Locomotion标签为0的数据item）';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.sit 结构
CREATE TABLE IF NOT EXISTS `sit` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `Time` text NOT NULL COMMENT '单位：ms',
  `RKN_accX` text NOT NULL COMMENT '单位：mg',
  `RKN_accY` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ` text NOT NULL COMMENT '单位：mg',
  `HIP_accX` text NOT NULL COMMENT '单位：mg',
  `HIP_accY` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ` text NOT NULL COMMENT '单位：mg',
  `LUA_accX` text NOT NULL COMMENT '单位：mg',
  `LUA_accY` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ` text NOT NULL COMMENT '单位：mg',
  `Locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；4：Sit；5：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Locomotion=4(Sit)';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.sit_33 结构
CREATE TABLE IF NOT EXISTS `sit_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `Time` text NOT NULL COMMENT '单位：ms',
  `RKN` text NOT NULL COMMENT '单位：mg',
  `HIP` text NOT NULL COMMENT '单位：mg',
  `LUA` text NOT NULL COMMENT '单位：mg',
  `Locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；4：Sit；5：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Locomotion=4(Sit)';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.stand 结构
CREATE TABLE IF NOT EXISTS `stand` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `Time` text NOT NULL COMMENT '单位：ms',
  `RKN_accX` text NOT NULL COMMENT '单位：mg',
  `RKN_accY` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ` text NOT NULL COMMENT '单位：mg',
  `HIP_accX` text NOT NULL COMMENT '单位：mg',
  `HIP_accY` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ` text NOT NULL COMMENT '单位：mg',
  `LUA_accX` text NOT NULL COMMENT '单位：mg',
  `LUA_accY` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ` text NOT NULL COMMENT '单位：mg',
  `Locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；4：Sit；5：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Locomotion=1(Stand)';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.stand_33 结构
CREATE TABLE IF NOT EXISTS `stand_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `Time` text NOT NULL COMMENT '单位：ms',
  `RKN` text NOT NULL COMMENT '单位：mg',
  `HIP` text NOT NULL COMMENT '单位：mg',
  `LUA` text NOT NULL COMMENT '单位：mg',
  `Locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；4：Sit；5：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Locomotion=1(Stand)';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.walk 结构
CREATE TABLE IF NOT EXISTS `walk` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `Time` text NOT NULL COMMENT '单位：ms',
  `RKN_accX` text NOT NULL COMMENT '单位：mg',
  `RKN_accY` text NOT NULL COMMENT '单位：mg',
  `RKN_accZ` text NOT NULL COMMENT '单位：mg',
  `HIP_accX` text NOT NULL COMMENT '单位：mg',
  `HIP_accY` text NOT NULL COMMENT '单位：mg',
  `HIP_accZ` text NOT NULL COMMENT '单位：mg',
  `LUA_accX` text NOT NULL COMMENT '单位：mg',
  `LUA_accY` text NOT NULL COMMENT '单位：mg',
  `LUA_accZ` text NOT NULL COMMENT '单位：mg',
  `Locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；4：Sit；5：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Locomotion=2(Walk)';

-- 数据导出被取消选择。


-- 导出  表 thesisexperiment.walk_33 结构
CREATE TABLE IF NOT EXISTS `walk_33` (
  `Id` int(10) NOT NULL AUTO_INCREMENT COMMENT '序列号',
  `Time` text NOT NULL COMMENT '单位：ms',
  `RKN` text NOT NULL COMMENT '单位：mg',
  `HIP` text NOT NULL COMMENT '单位：mg',
  `LUA` text NOT NULL COMMENT '单位：mg',
  `Locomotion` text NOT NULL COMMENT '1：Stand；2：Walk；4：Sit；5：Lie',
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Locomotion=2(Walk)';

-- 数据导出被取消选择。
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
